
NUMBER = int(input("ENTER A NUMBER TO CALCULATE ITS FACTORIAL: "))

IF NUMBER < 0:
    PRINT("FACTORIAL IS NOT DEFINED FOR NEGATIVE NUMBERS.")
ELIF NUMBER == 0:
    PRINT("THE FACTORIAL OF 0 IS 1.")
ELSE:
    FACTORIAL = 1
    FOR I IN RANGE(1, NUMBER + 1):
        FACTORIAL *= I
    PRINT(f"THE FACTORIAL OF {NUMBER} IS {FACTORIAL}.")
